version: '3.8'
services:
  app:
    build:
      context: ./bank
      dockerfile: ./Dockerfile.dev
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=bank/app.py
      - POSTGRES_URL=db
    env_file:
      - db.env
    volumes:
      - ./bank:/var/code:delegated
    command:
      ./wait-pg.sh ./start.sh
  atm:
    build:
      context: ./atm
      dockerfile: ./Dockerfile.dev
    restart: always
    environment:
      - BANK_HOST=app
      - BANK_PORT=5000
    depends_on:
      - app
    volumes:
      - ./atm:/var/code:delegated
    command:
      sleep infinity
  db:
    image: "postgres"
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
